### ISSUE TITLE
The 'common.min.js' file not in repo

### ISSUE THREAD

**Issue by alex-hsa** [forumone/gesso-uswds#120]
Hello:

The guswds.libraries.yml file includes the 'js/dist/common.min.js' file on line #4, however this file is currently not part of the repo.

Is the 'js/dist/common.min.js' file necessary to run the theme smoothly?

Thank you very much.

**Comment by coreylafferty** [comment]
Thank you for the question, @alex-hsa.  The files in the js/dist/ directory are generated when you run the gulp task, so that's why the file is not in the repo.  Once you run `npm install` and `gulp` or `gulp build`, the files in that directory should show up.

However, while looking into your question I realized that a recent change to the theme makes it so that particular file 'common.min.js' isn't generated with our out-of-the-box JS scripts.  I'm going to consult with some other developers and determine what change we need to make due to that, but in the meantime I think you can either ignore it for now as that file missing really shouldn't cause any major issues or, if you like, you can change line 22 of `webpack.config.js` from:

```
minChunks: 2,
```

to

```
minChunks: 1,
```

and then the file will definitely be generated.

**Comment by coreylafferty** [comment]
@alex-hsa There's a PR accepted into the dev branch to address this issue that will be part of the next release.  If you wish to add those changes to your theme, just make the same changes shown here:

https://github.com/forumone/gesso-uswds/pull/121/files

After those changes are in place, the theme will only load the common.min.js file if it is generated by the Gulp task.

**Comment by alex-hsa** [comment]
@coreylafferty, thank you very much for providing a work-around as well as a permanent solution via PR #121, which I appreciated very much.
